UPDATE l SET l.rota_frontend = m.rota
FROM Localizacao l
INNER JOIN (VALUES
    ('Serra da Capivara',                     '/pi/serra-da-capivara'),
    ('Delta do Parnaíba',                     '/pi/delta-do-parnaiba'),
    ('Parque Nacional Sete Cidades',          '/pi/sete-cidades'),
    ('Luís Correia',                          '/pi/luis-correia'),
    ('Pedra do Castelo',                      '/pi/pedra-do-castelo'),
    ('Centro Histórico de Teresina',          '/pi/teresina-centro'),
    ('Dunas de Genipabu',                     '/rn/genipabu'),
    ('Praia de Pipa',                         '/rn/pipa'),
    ('Maracajaú',                             '/rn/maracajau'),
    ('Parque das Dunas',                      '/rn/parque-das-dunas'),
    ('Forte dos Reis Magos',                  '/rn/forte-dos-reis-magos'),
    ('Baía Formosa',                          '/rn/baia-formosa'),
    ('Gramado',                               '/rs/gramado'),
    ('Cânion Itaimbezinho',                   '/rs/canion-itaimbezinho'),
    ('Bento Gonçalves',                       '/rs/bento-goncalves'),
    ('Porto Alegre',                          '/rs/porto-alegre'),
    ('Torres',                                '/rs/torres'),
    ('São Miguel das Missões',                '/rs/sao-miguel-das-missoes'),
    ('Florianópolis',                         '/sc/florianopolis'),
    ('Balneário Camboriú',                    '/sc/balneario-camboriu'),
    ('Bombinhas',                             '/sc/bombinhas'),
    ('Blumenau',                              '/sc/blumenau'),
    ('São Joaquim',                           '/sc/sao-joaquim'),
    ('Joinville',                             '/sc/joinville'),
    ('MASP',                                  '/sp/masp'),
    ('Cânion do Xingó',                       '/sergipe/canion-xingo'),
    ('Monte Roraima',                         '/roraima/monte-roraima'),
    ('Parque Nacional do Monte Roraima',      '/roraima/parque-monte-roraima'),
    ('Lavrado de Roraima',                    '/roraima/lavrado'),
    ('Museu Estrada de Ferro Madeira-Mamoré', '/rondonia/ferrovia-madeira-mamore'),
    ('Lago de Samuel',                        '/rondonia/lago-samuel'),
    ('Catedral Nossa Senhora das Graças',     '/rondonia/catedral-porto-velho'),
    ('Reserva Biológica do Jaru',             '/rondonia/reserva-jaru'),
    ('Ilha do Bananal',                       '/tocantins/ilha-do-bananal'),
    ('Orla de Palmas',                        '/tocantins/orla-de-palmas'),
    ('Catedral Nossa Senhora da Assunção',    '/tocantins/catedral-palmas'),
    ('Cachoeira da Serra do Lajeado',         '/tocantins/serra-lajeado'),
    ('Feira Gastronômica de Palmas',          '/tocantins/feira-gastronomica'),
    ('Jalapão',                               '/tocantins/jalapao')
) AS m(nome, rota) ON l.nome = m.nome;
